# This is a config for E2B sandbox template.
# You can use template ID (6twftqc6clsqzyugo9xn) or template name (coderai-nextjs-test-8) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("coderai-nextjs-test-8") # Sync sandbox
# sandbox = await AsyncSandbox.create("coderai-nextjs-test-8") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('coderai-nextjs-test-8')

team_id = "4e442f88-3883-4416-9ba7-7e1c8e3a373b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "coderai-nextjs-test-8"
template_id = "6twftqc6clsqzyugo9xn"
